import { Inter } from "next/font/google";
import "./globals.css";
import TaskBar from "@/components/taskBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: inter }} className="bg-black ">
        {children}
      </body>
    </html>
  );
}
